### PR TITLE
pkg/cpu: Reduce .text section error spam

### LINKED ISSUE #1857: Could not find `.text` section spams error log
My logs are being spammed with the error message:

```
level=error name=parca-agent ts=2023-07-13T16:16:20.242517888Z caller=cpu.go:308 component=cpu_profiler msg="failed to add unwind table" pid=1890187 err="setUnwindTableForMapping for
 executable /root/.julia/artifacts/37805a06093bdc0d5938601719cf02fa0cf3aa68/lib/rr/librrpage.so starting at 0x6fffd000 failed: BuildID failed /proc/1890187/root/root/.julia/artifacts/37805a06093bdc0d5938601719cf02fa0cf3aa68/lib/rr/librrpage.so: could not find .text section"
```

It would be better if the error would only be reported once.

### PR DESCRIPTION
**Pull request by Sylfrena**
Fixes #1857

### Why?
User report that logs are being spammed with 

```
level=error name=parca-agent ts=2023-07-13T16:16:20.242517888Z caller=cpu.go:308 component=cpu_profiler msg="failed to add unwind table" pid=1890187 err="setUnwindTableForMapping for executable /root/.julia/artifacts/37805a06093bdc0d5938601719cf02fa0cf3aa68/lib/rr/librrpage.so starting at 0x6fffd000 failed: BuildID failed /proc/1890187/root/root/.julia/artifacts/37805a06093bdc0d5938601719cf02fa0cf3aa68/lib/rr/librrpage.so: could not find .text section"
```

in #1857

### What?
Add a counter to keep track of said error and only logs it once every 50 times we hit the error case to reduce spamming the logs in default logging mode.
 

### <samp>🤖 Generated by Copilot at 502844c</samp>

> _We search for the text in the maps of the dead_
> _But sometimes we find nothing but `ErrTextSectionNotFound`_
> _We track the errors and we log the doom_
> _We need the unwind tables to escape the CPU's tomb_

-->

### CODE REVIEW

File: pkg/profiler/cpu/cpu.go [hunk 1]
```diff
@@ -304,6 +308,13 @@ func (p *CPU) addUnwindTableForProcess(pid int) {
 			level.Debug(p.logger).Log("msg", "failed to add unwind table due to a procfs race", "pid", pid, "err", err)
 		} else if errors.Is(err, errTooManyExecutableMappings) {
 			level.Warn(p.logger).Log("msg", "failed to add unwind table due to having too many executable mappings", "pid", pid, "err", err)
+		} else if errors.Is(err, ErrTextSectionNotFound) {
+			if p.processErrorTracker[err]%50 == 0 {
+				level.Error(p.logger).Log("msg", "failed to add unwind table due to unavailable .text section", "pid", pid, "err", err)
+			} else {
+				level.Debug(p.logger).Log("msg", "failed to add unwind table due to unavailable .text section", "pid", pid, "err", err)
+			}
+			p.processErrorTracker[err] = p.processErrorTracker[err] + 1
```
Comment (brancz) [inline pkg/profiler/cpu/cpu.go:317]: shorten to `p.processErrorTracker[err]++`

File: pkg/profiler/cpu/cpu.go [hunk 2]
```diff
@@ -304,6 +308,13 @@ func (p *CPU) addUnwindTableForProcess(pid int) {
 			level.Debug(p.logger).Log("msg", "failed to add unwind table due to a procfs race", "pid", pid, "err", err)
 		} else if errors.Is(err, errTooManyExecutableMappings) {
 			level.Warn(p.logger).Log("msg", "failed to add unwind table due to having too many executable mappings", "pid", pid, "err", err)
+		} else if errors.Is(err, ErrTextSectionNotFound) {
+			if p.processErrorTracker[err]%50 == 0 {
```
Comment (brancz) [inline pkg/profiler/cpu/cpu.go:312]: let's make this 50 at least a configurable field on the `CPU` struct, so we can potentially make it a flag if we wanted to one day

File: pkg/profiler/cpu/cpu.go [hunk 3]
```diff
@@ -280,6 +283,7 @@ func loadBpfProgram(logger log.Logger, reg prometheus.Registerer, mixedUnwinding
 
 func (p *CPU) addUnwindTableForProcess(pid int) {
 	executable := fmt.Sprintf("/proc/%d/exe", pid)
+	//p.processErrorTracker = map[error]int{}
```
Comment (brancz) [inline pkg/profiler/cpu/cpu.go:286]: leftover?

File: pkg/profiler/cpu/maps.go [hunk 4]
```diff
@@ -151,6 +151,7 @@ var (
 	errUnrecoverable             = errors.New("unrecoverable error")
 	errTooManyExecutableMappings = errors.New("too many executable mappings")
 	ErrNeedMoreProfilingRounds   = errors.New("not enough profiling rounds with this unwind info")
+	ErrTextSectionNotFound       = errors.New("could not find .text section")
```
Comment (brancz) [inline pkg/profiler/cpu/maps.go:154]: We don't actually return this error anywhere so the `errors.Is` above won't work.

File: pkg/profiler/cpu/cpu.go [hunk 5]
```diff
@@ -158,6 +159,8 @@ func NewCPUProfiler(
 
 		memlockRlimit: memlockRlimit,
 
+		processErrorTracker: map[error]int{},
```
Comment (brancz) [inline pkg/profiler/cpu/cpu.go:162]: the `error` type can behave a bit weird here, I think we should just use `string` and use `err.Error()`

Comment (brancz) [inline pkg/profiler/cpu/cpu.go:162]: I'm a bit worried about this being unbounded, let's use a capped cache implementation instead.

**Review by brancz — COMMENTED** [review]
Nice yes this is exactly the type of direction I was thinking of.

File: pkg/profiler/cpu/cpu.go [hunk 6]
```diff
@@ -304,6 +308,13 @@ func (p *CPU) addUnwindTableForProcess(pid int) {
 			level.Debug(p.logger).Log("msg", "failed to add unwind table due to a procfs race", "pid", pid, "err", err)
 		} else if errors.Is(err, errTooManyExecutableMappings) {
 			level.Warn(p.logger).Log("msg", "failed to add unwind table due to having too many executable mappings", "pid", pid, "err", err)
+		} else if errors.Is(err, ErrTextSectionNotFound) {
+			if p.processErrorTracker[err]%50 == 0 {
+				level.Error(p.logger).Log("msg", "failed to add unwind table due to unavailable .text section", "pid", pid, "err", err)
```
Comment (kakkoyun) [inline pkg/profiler/cpu/cpu.go:313]: nit: It would be nice to see the number of encounters so far in the logs.
```suggestion
				level.Error(p.logger).Log("msg", "failed to add unwind table due to unavailable .text section", "pid", pid, "err", err, "encounters", p.processErrorTracker[err])
```

File: pkg/profiler/cpu/maps.go (hunk 4 above)
Comment (kakkoyun) [reply pkg/profiler/cpu/maps.go:154]: And if this doesn't cross the package boundary, maybe we should consider not exporting it?

File: pkg/profiler/cpu/cpu.go (hunk 6 above)
Comment (brancz) [reply pkg/profiler/cpu/cpu.go:313]: I like this

File: pkg/profiler/cpu/maps.go (hunk 4 above)
Comment (Sylfrena) [reply pkg/profiler/cpu/maps.go]: agreed! 
it was a typo on my end, but thanks so much for catching it!

File: pkg/profiler/cpu/maps.go [hunk 7]
```diff
@@ -959,6 +960,9 @@ func (m *bpfMaps) setUnwindTableForMapping(buf *profiler.EfficientBuffer, pid in
 	}
 	buildID, err := buildid.FromELF(ef)
 	if err != nil {
+		if errors.Is(err, errTextSectionNotFound) {
+			return fmt.Errorf("BuildID failed %s: %w", fullExecutablePath, errTextSectionNotFound)
```
Comment (brancz) [inline pkg/profiler/cpu/maps.go:964]: we should just use `err` in the last argument here

File: pkg/profiler/cpu/maps.go [hunk 8]
```diff
@@ -959,6 +960,9 @@ func (m *bpfMaps) setUnwindTableForMapping(buf *profiler.EfficientBuffer, pid in
 	}
 	buildID, err := buildid.FromELF(ef)
 	if err != nil {
+		if errors.Is(err, errTextSectionNotFound) {
```
Comment (brancz) [inline pkg/profiler/cpu/maps.go:963]: `buildid.FromELF` never actually return the `errTextSectionNotFound` so we will never go into this if. We need to move the error to the buildid package and return it here: https://github.com/parca-dev/parca-agent/blob/cefb78dc9c5582a57b2bbe62dd9fae3a0b20033b/pkg/buildid/elf.go#L66

Then we can check whether we're getting that error in this if with `if errors.Is(err, buildid.ErrTextSectionNotFound)`

File: pkg/profiler/cpu/cpu.go [hunk 9]
```diff
@@ -158,6 +161,9 @@ func NewCPUProfiler(
 
 		memlockRlimit: memlockRlimit,
 
+		// increase cache length if needed to track more errors
+		processErrorTracker: cache.NewLRUCache[string, int](prometheus.WrapRegistererWith(prometheus.Labels{"cache": "error_tracker"}, reg), 1),
```
Comment (brancz) [inline pkg/profiler/cpu/cpu.go:165]: 1 entry is not going to be enough, since this can happen for X amount of processes, and even N amount of mappings within those processes

Comment (brancz) [reply pkg/profiler/cpu/cpu.go:165]: Also let's choose a better name `error_tracker` is a bit too generic, maybe `no_text_section_error_tracker`?

File: pkg/profiler/cpu/cpu.go [hunk 10]
```diff
@@ -304,6 +310,19 @@ func (p *CPU) addUnwindTableForProcess(pid int) {
 			level.Debug(p.logger).Log("msg", "failed to add unwind table due to a procfs race", "pid", pid, "err", err)
 		} else if errors.Is(err, errTooManyExecutableMappings) {
 			level.Warn(p.logger).Log("msg", "failed to add unwind table due to having too many executable mappings", "pid", pid, "err", err)
+		} else if errors.Is(err, buildid.ErrTextSectionNotFound) {
+			v, ok := p.processErrorTracker.Peek(err.Error())
```
Comment (brancz) [inline pkg/profiler/cpu/cpu.go:314]: What's the full error string here again? We should make sure it contains the PID and/or mapping file path.

Comment (Sylfrena) [reply pkg/profiler/cpu/cpu.go:314]: I think we should be good here already. The [reported error string](https://github.com/parca-dev/parca-agent/issues/1857#issue-1803351339)(as seen below) already contains pid and mapping start address and mapping file path.
> `level=error name=parca-agent ts=2023-07-13T16:16:20.242517888Z caller=cpu.go:308 component=cpu_profiler msg="failed to add unwind table" pid=1890187 err="setUnwindTableForMapping for
 executable /root/.julia/artifacts/37805a06093bdc0d5938601719cf02fa0cf3aa68/lib/rr/librrpage.so starting at 0x6fffd000 failed: BuildID failed /proc/1890187/root/root/.julia/artifacts/37805a06093bdc0d5938601719cf02fa0cf3aa68/lib/rr/librrpage.so: could not find .text section"`

File: pkg/profiler/cpu/cpu.go (hunk 9 above)
Comment (Sylfrena) [reply pkg/profiler/cpu/cpu.go:165]: Cool I was thinking maybe we could eventually reuse the cache to log different errors too but no strong opinions :D

File: pkg/buildid/elf.go [hunk 11]
```diff
@@ -26,6 +26,10 @@ import (
 
 const goBuildIDSectionName = ".note.go.buildid"
 
+var (
+	ErrTextSectionNotFound = errors.New("could not find .text section")
+)
```
Comment (Sylfrena) [inline pkg/buildid/elf.go:31]:
```suggestion
var ErrTextSectionNotFound = errors.New("could not find .text section") 
```

**Review by brancz — APPROVED** [review]
